apiVersion: v1
kind: Pod
metadata:
  name: hands-on-2
  labels:
    version: "1"
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: share-volume
    - name: busybox
      image: busybox:latest
      command:
        - watch
        - echo 'Hands on 2 demo' > /tmp/index.html
      volumeMounts:
        - mountPath: /tmp
          name: share-volume
  volumes:
    - name: share-volume
      emptyDir: {}