apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_passwd: YWRtaW4= #admin
  user: YmxvZ190ZXN0 #blog_test
  user_passwd: cGFzc3dvcmQ= #password
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cfgmap
data:
  db_host: mysql-svc
  db_name: Test_1234
