apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/log/nginx
          name: log-vol
        - name: nginx-vol
          mountPath: "/etc/nginx"
      - image: fluentd:latest
        name: fluentd
        volumeMounts:
        - mountPath: /logs
          name: log-vol
        - name: fluentd-vol
          mountPath: "/fluentd/etc"
      volumes:
      - name: log-vol
        hostPath:
          path: /var/log
          type: DirectoryOrCreate
      - name: nginx-vol
        configMap:
          name: nginx-cfgmap
      - name: fluentd-vol
        configMap:
          name: fluentd-cfgmap

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    app: nginx