apiVersion: apps/v1
kind: Deployment
metadata:
  name: hands-on-3-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod-1
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: nginx
          resources:
            requests:
              cpu: 50m
              memory: "50Mi"
            limits:
              cpu: 100m
              memory: "100Mi"          
          livenessProbe:
            httpGet:
              port: 80
              path: /
            failureThreshold: 3
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 80